const mongoose = require("mongoose");
const { Schema } = mongoose;

const cardEmbossingModel = new Schema({
  INSTITUTION_ID: { type: Number, required: true },
  SERNO: { type: Number, required: true },
  PRODUCTIONPROFILE: { type: Number },
  SECURITYPROFILE: { type: Number, required: true },
  EMBNAME: { type: String, required: true },
  EMBCOMPANY: { type: String },
  EMBVALIDFROM: { type: Date },
  EMBNOPIN: { type: Number },
  EMBPINENCRYPTIONKEYTYPE: { type: Number },
  EMBPIN: { type: String },
  EMBPINOFFSET: { type: String },
  EMBPREVPINOFFSET: { type: String },
  EMBPVV: { type: String },
  TELECODE: { type: String },
  TELEBANKPIN: { type: String },
  TELEBANKPVV: { type: String },
  REISSUECOUNT: { type: Number },
  REISSUEDATE: { type: Date },
  RENEWDATE: { type: Date },
  LOGACTION: { type: String },
  EMBPVKI: { type: String },
  EMBPREVPIN: { type: String },
  EMBPREVPVV: { type: String },
  EMBPREVPVKI: { type: String },
  EMBPINBACKUP: { type: String },
  EMBPREVPINBACKUP: { type: String },
  EMBSENDPVV: { type: Number },
  CARDSEQUENCE: { type: Number, required: true },
  CARDTYPE: { type: String, required: true },
  CARDINTERFACE: { type: Number },
  CHIPAPPLCODE: { type: String },
  LASTUPDATED: { type: Date },
  EMBOSSINGNAMEFROMPERSON: { type: Number, required: true },
  CONVERTED: { type: Number },
});

module.exports = mongoose.model("cardEmbossing", cardEmbossingModel);
