const mongoose = require("mongoose");
const { Schema } = mongoose;

const cardStatusXModel = new Schema({
  INSTITUTION_ID: { type: Number, required: true },
  PSERNO: { type: Number, required: true },
  CODE: { type: String, required: true },
  DESCRIPTION: { type: String, required: true },
  CARD: { type: Number, required: true },
  ACCOUNT: { type: Number, required: true },
  CUSTOMER: { type: Number, required: true },
  RISKDOMAIN: { type: Number, required: true },
  COLINVOICE: { type: Number, required: true },
  GENERAL: { type: Number, required: true },
  FINANCIAL: { type: Number, required: true },
  EMBOSSING: { type: Number, required: true },
  AUTH: { type: Number, required: true },
  TRXNREJECT: { type: Number, required: true },
  AUTHMAP: { type: String },
  BILLABLE: { type: Number, required: true },
  STOPRENEW: { type: Number, required: true },
  STOPREPLACE: { type: Number, required: true },
  STOPREISSUE: { type: Number, required: true },
  HOLDSERVICEFEES: { type: Number, required: true },
  SUPPRESSFEES: { type: Number, required: true },
  SUPPRESSREDEMPTION: { type: Number, required: true },
  SUPPRESSINTEREST: { type: Number, required: true },
  DELINQUENT: { type: Number, required: true },
  STICKY: { type: Number, required: true },
  STMTPRINTNOTSEND: { type: Number },
  CLOSED: { type: Number, required: true },
  STATUSTYPE: { type: Number, required: true },
  STOPMAILING: { type: Number },
  CANCELINSURANCE: { type: Number },
  NOTIFYBUREAU: { type: Number },
  PRIORITY: { type: Number },
  ACCOUNTTYPES: { type: String },
  MAPFINANCIAL: { type: String },
  MAPEMBOSSING: { type: String },
  MAPAUTHORIZATION: { type: String },
  MAPCARD: { type: String },
  MAPACCOUNT: { type: String },
  MAPCUSTOMER: { type: String },
  MAPLEVELUPSTATUS: { type: String },
  MAPLEVELUPDEPTH: { type: Number },
  MAPLEVELDOWNSTATUS: { type: String },
  MAPLEVELDOWNDEPTH: { type: Number },
  ALLOWSTMTINSTALMENTOFFERS: { type: Number },
  AMEXREASONCODE: { type: String },
  NEGATIVEREASONCODES: { type: String },
  ADDSERVICE: { type: String },
  ADDSERVICELOGACTION: { type: String },
  CURRACTIVATIONSTATUS: { type: String },
  PREVACTIVATIONSTATUS: { type: String },
  CUSTOMERGENERALPERMISSIONID: { type: Number },
  ACCOUNTGENERALPERMISSIONID: { type: Number },
  ACCOUNTFINANCIALPERMISSIONID: { type: Number },
  ACCOUNTAUTHPERMISSIONID: { type: Number },
  CARDGENERALPERMISSIONID: { type: Number },
  CARDFINANCIALPERMISSIONID: { type: Number },
  CARDEMBOSSINGPERMISSIONID: { type: Number },
  CARDAUTHPERMISSIONID: { type: Number },
  ACCCLOSEOPTION: { type: Number },
  ACCELERATEINSTALMENTS: { type: Number },
  OVERRIDEINTREFUNDMETHODONACCL: { type: Number },
  WAIVEACCELERATIONFEE: { type: Number },
  EXCLUDE3DENROLMENT: { type: Number },
  LOGVERSION: { type: Number },
});

module.exports = mongoose.model("cardStatusX", cardStatusXModel);
