const mongoose = require("mongoose");
const { Schema } = mongoose;

const cardXModel = new Schema({
  INSTITUTION_ID: { type: Number, required: true },
  SERNO: { type: Number, required: true },
  CACCSERNO: { type: Number, required: true },
  NUMBERX: { type: String, required: true },
  PRIMARYCARD: { type: Number, required: true },
  PEOPLESERNO: { type: Number, required: true },
  RISKDOMAINSERNO: { type: Number },
  PRODUCT: { type: Number, required: true },
  FEEPROFSERNO: { type: Number },
  TRXNFEEPROFSERNO: { type: Number },
  INSTPROFSERNO: { type: Number },
  REWARDPROFSERNO: { type: Number },
  CAPROFSERNO: { type: Number },
  SERVICEFEEOVERRIDESEXIST: { type: Number, required: true },
  TRXNFEEOVERRIDESEXIST: { type: Number, required: true },
  SERVICECODE: { type: String },
  EXPIRYDATE: { type: Date },
  EXPIRYDATESTATUS: { type: String },
  EXPIRYPERIODRENEW: { type: Number },
  PREVIOUSEXPIRYDATE: { type: Date },
  PREVEXPIRYDATESTATUS: { type: String },
  CREATEDATE: { type: Date },
  BLOCKEDDATE: { type: Date },
  CLOSEDATE: { type: Date },
  OLDCARDSERNO: { type: Number },
  NEWCARDSERNO: { type: Number },
  STGENERAL: { type: String, required: true },
  STFINANCIAL: { type: String, required: true },
  STAUTHORIZATION: { type: String, required: true },
  STEMBOSSING: { type: String, required: true },
  PRECHANGEREQUESTSTGENERAL: { type: String },
  MASTERPROFILESERNO: { type: Number },
  REALFLAG: { type: Number },
  CARDCOUNTRY: { type: String },
  VIRTUAL: { type: Number, required: true },
  APPLICATIONSERNO: { type: Number },
  ACCSTMTSUMMARYIND: { type: Number },
  SENDMEMOSTATEMENT: { type: Number },
  LOGACTION: { type: String },
  DEFAULTACCOUNTTYPE: { type: String },
  INSTANTISSUANCE: { type: Number },
  LANGUAGECODE: { type: String },
  PVVVERSIONNO: { type: Number },
  CARDACTIVEVERSIONNO: { type: Number },
  ENTITYVERSIONNO: { type: Number },
  EXTERNALREFERENCE: { type: String },
  ACSENROLMENTSTATUS: { type: String },
  ACSPASSWORDMODEL: { type: Number },
  CONVERTED: { type: Number },
  AUTHFEEPROFSERNO: { type: Number },
  PRIORITYPASSCARD: { type: Number },
  PRIORITYPASSCARDSERNO: { type: Number },
});

module.exports = mongoose.model("cardX", cardXModel);
