const mongoose = require("mongoose");
const { Schema } = mongoose;

const cTransactionsModel = new Schema({
  INSTITUTION_ID: { type: Number, required: true },
  SERNO: { type: Number, required: true },
  PARTITIONKEY: { type: Number, required: true },
  CACCSERNO: { type: Number },
  CARDSERNO: { type: Number },
  DEF_CACCSERNO: { type: Number },
  PRODUCT: { type: Number },
  BATCHSERNO: { type: Number, required: true },
  TYPESERNO_ALLOC: { type: Number },
  TYPESERNO_FEES: { type: Number },
  TYPESERNO_REPORTS: { type: Number },
  TYPESERNO_REWARDS: { type: Number },
  TYPESERNO_GLEDGER: { type: Number },
  TYPESERNO_DIVERT: { type: Number },
  TYPESERNO_NOPOST: { type: Number },
  TYPESERNO_PROBE: { type: Number },
  TYPESERNO_TEXT: { type: Number },
  MSGCLASS: { type: Number },
  MSGTYPE: { type: Number },
  TRXNTYPE: { type: Number },
  ORIG_MSG_TYPE: { type: String, required: true },
  I000_MSG_TYPE: { type: String, required: true },
  I002_NUMBER: { type: String, required: true },
  I003_PROC_CODE: { type: String, required: true },
  I004_AMT_TRXN: { type: Number },
  I005_AMT_SETTLE: { type: Number },
  I006_AMT_BILL: { type: Number },
  I007_LOAD_DATE: { type: Date, required: true },
  I008_BILLING_FEE: { type: Number },
  I013_TRXN_DATE: { type: Date, required: true },
  I044_REASON_CODE: { type: String },
  I048_TEXT_DATA: { type: String },
  I049_CUR_TRXN: { type: String },
  I050_CUR_SETTLE: { type: String },
  I051_CUR_BILL: { type: String },
  INSTALMENTTYPE: { type: Number },
  INSTALMENTINDEPFLAG: { type: Number },
  INSTALMENTSNUMBER: { type: Number },
  INSTALMENTSEQ: { type: Number },
  INSTALMENTREPAYMENTTYPE: { type: Number },
  INSTALMENTOFFSET: { type: Number },
  INSTALMENTORIGAMOUNT: { type: Number },
  INSTALMENTTOTALAMOUNT: { type: Number },
  INSTALMENTPLANSERNO: { type: Number },
  INSTALMENTINTERESTANCHORDATE: { type: Date },
  INSTALMENTSERNO: { type: Number },
  INSTALMENTPARTITIONKEY: { type: Number },
  INSTALMENTAMRTPRINCIPALAMOUNT: { type: Number },
  SINGLE_MSG_FLAG: { type: Number },
  AUTHIMMEDIATEPOSTING: { type: String },
  AUTHACCOUNTTYPE: { type: String },
  AUTHAMOUNT: { type: Number },
  ORIGINATOR: { type: String },
  ORIGINATORREASONCODE: { type: String },
  PROXYCARDNUMBER: { type: String },
  INVOICENUMBER: { type: String },
  AMOUNT: { type: Number, required: true },
  EMBEDDEDFEE: { type: Number, required: true },
  TOTALPOINTS: { type: Number },
  TOTALREBATES: { type: Number, required: true },
  TAXFLAG: { type: Number },
  TAXBASEAMOUNT: { type: Number },
  VALUEDATE: { type: Date },
  STARTOFINTEREST: { type: Date },
  MINDUEVALUEDATE: { type: Date },
  POSTDATE: { type: Date },
  POSTTIMESTAMP: { type: Date },
  TEXTDESCRIPTION: { type: String },
  FGRESOLUTIONSTATUS: { type: String },
  STGENERAL: { type: String, required: true },
  LOGACTION: { type: String },
  CONVERTED: { type: Number },
  CONSOLIDATIONKEY: { type: Number },
  REWARDSFLAG: { type: Number },
  MBHAGREEMENTSERNO: { type: Number },
});

module.exports = mongoose.model("cTransactions", cTransactionsModel);
